/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BGP: typeof import('./src/components/Utilities/BGP.vue')['default']
    Copy: typeof import('./src/components/Copy.vue')['default']
    FileSpeedtest: typeof import('./src/components/Speedtest/FileSpeedtest.vue')['default']
    Information: typeof import('./src/components/Information.vue')['default']
    IPerf3: typeof import('./src/components/Utilities/IPerf3.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Librespeed: typeof import('./src/components/Speedtest/Librespeed.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MTR: typeof import('./src/components/Utilities/MTR.vue')['default']
    MTR6: typeof import('./src/components/Utilities/MTR6.vue')['default']
    NodeList: typeof import('./src/components/Utilities/NodeList.vue')['default']
    NodeSelector: typeof import('./src/components/NodeSelector.vue')['default']
    Ping: typeof import('./src/components/Utilities/Ping.vue')['default']
    Ping6: typeof import('./src/components/Utilities/Ping6.vue')['default']
    SafeHtml: typeof import('./src/components/SafeHtml.vue')['default']
    Shell: typeof import('./src/components/Utilities/Shell.vue')['default']
    Speedtest: typeof import('./src/components/Speedtest.vue')['default']
    SpeedtestNet: typeof import('./src/components/Utilities/SpeedtestNet.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    Traceroute: typeof import('./src/components/Utilities/Traceroute.vue')['default']
    Traceroute6: typeof import('./src/components/Utilities/Traceroute6.vue')['default']
    TrafficDisplay: typeof import('./src/components/TrafficDisplay.vue')['default']
    Utilities: typeof import('./src/components/Utilities.vue')['default']
  }
}
