/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Copy: typeof import('./src/components/Copy.vue')['default']
    FileSpeedtest: typeof import('./src/components/Speedtest/FileSpeedtest.vue')['default']
    Information: typeof import('./src/components/Information.vue')['default']
    IPerf3: typeof import('./src/components/Utilities/IPerf3.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Librespeed: typeof import('./src/components/Speedtest/Librespeed.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Ping: typeof import('./src/components/Utilities/Ping.vue')['default']
    Shell: typeof import('./src/components/Utilities/Shell.vue')['default']
    Speedtest: typeof import('./src/components/Speedtest.vue')['default']
    SpeedtestNet: typeof import('./src/components/Utilities/SpeedtestNet.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TrafficDisplay: typeof import('./src/components/TrafficDisplay.vue')['default']
    Utilities: typeof import('./src/components/Utilities.vue')['default']
  }
}
